### ISSUE TITLE
Suggestion: allow use of PgUp and PgDown scrolling (among other suggestions)

### ISSUE THREAD

**Issue by mknepper** [rajasegar/alacritty-themes#10]
So, like the title says. Here are some suggestions I think that would streamline the theme selector.

1. Allow use of PgUp and PgDown for scrolling (this goes faster than using arrow up and down one at a time).
2. Theme previews (hovering over a theme shows a preview of what it will look like, either by temporarily themeing Alacritty or something)

I'm not sure how possible this is with npm/node.

**Comment by rajasegar** [comment]
I am not sure using Page up and down is possible, but you can always fuzzy search by typing the characters
The second issue is fixed in latest version 3.0.0

**Comment by paulo-santana** [comment]
I'm running it on Arch Linux with npx and PgUp and PgDown are working fine. I guess it's the default behaviour of propmts. If you're using Mac, on their API page they say that you should use <kbd>fn</kbd> + <kbd>⇧</kbd> / <kbd>⇩</kbd> instead.
https://github.com/terkelg/prompts#autocompletemessage-choices-initial-suggest-limit-stylec:

**Comment by JuanVqz** [comment]
I'm closing this issue because we don't have enough information, and it seems one user is able to use it as expected.
