### ISSUE TITLE
Cannot read property 'items' of null

### ISSUE THREAD

**Issue by iBhavesh** [rajasegar/alacritty-themes#12]
node_modules/alacritty-themes/index.js:39
  const colors = doc.contents.items.filter((i) => i.key.value === 'colors')[0];
  
  TypeError: Cannot read property 'items' of null
    at updateTheme (/usr/lib/node_modules/alacritty-themes/index.js:39:31)
    at /usr/lib/node_modules/alacritty-themes/index.js:68:5
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:75:3)

**Comment by rajasegar** [comment]
Looks like there is no alacritty.ym file or it might be empty.
Can you try creating one with this
```
alacritty-themes --create
```
and then try the themes
