### ISSUE TITLE
Option to pass themes directory

### ISSUE THREAD

**Issue by reportaman** [rajasegar/alacritty-themes#123]
Provide a command line option to specify directory for themes. iTerm2 color themes are the best curated, and available for a range of terminals including Alacritty. A command line option to specify path for themes will make life easy (no merge conflicts between that project and this) and open possibility to have other themes: https://github.com/mbadolato/iTerm2-Color-Schemes

**Comment by stephanospavlou** [comment]
@reportaman The feature you've requested has been added!

**Comment by JuanVqz** [comment]
solved #144
