### ISSUE TITLE
This library broke alacritty and deleted my config.. 👎👎👎👎

### ISSUE THREAD

**Issue by joe-narvaez** [rajasegar/alacritty-themes#131]
:(

**Comment by JuanVqz** [comment]
hey, @joe-narvaez I'm sorry about that :pray: , we may solve it did you remember what did you do when it happened?

**Comment by rajasegar** [comment]
I think we should give some sort of escape hatch to the users if we have problems like these. May be something like always creating a backup for the config file, before modifying it for preview and apply themes. So the users can just rename/move/copy the backup file to restore the settings.
@joe-narvaez @h45h1r Sincere apologies for the inconvenience caused.
@JuanVqz What are your thoughts?

**Comment by rajasegar** [comment]
Just outlining the steps here: 
- [ ] Create a backup file in the same config directory with timestamp to ensure that we are not overwriting any existing backups
- [ ] Add documentation to README about the steps to how to restore the original config

**Comment by h45h1r** [comment]
What if you create a backup file and delete the older versions of the backup each time

**Comment by h45h1r** [comment]
> Aside note:I think this error is showing up when you are moving between themes fast. 

Yes, I changed the theme a few times before this happened

**Comment by JuanVqz** [comment]
> I think we should give some sort of escape hatch to the users if we have problems like these. May be something like always creating a backup for the config file, before modifying it for preview and apply themes. So the users can just rename/move/copy the backup file to restore the settings.
> 
> @joe-narvaez @h45h1r Sincere apologies for the inconvenience caused.
> 
> @JuanVqz What are your thoughts?

@rajasegar I'm thinking users will end up in the same scenario if we create a backup each time they select a new theme. We may create corrupt backups.

What about to add the option: `alacritty-themes --backup` and let them use it when they want.

**Comment by rajasegar** [comment]
No no, not each time they select a new theme, but only one time when they invoke the program before even showing the prompts.

**Comment by JuanVqz** [comment]
> No no, not each time they select a new theme, but only one time when they invoke the program even before showing the prompts.

sounds good! I'll check it
