### ISSUE TITLE
Remove Node 12 from the CI workflows

### ISSUE THREAD

**Issue by rajasegar** [rajasegar/alacritty-themes#145]
Since Node 12 is EOL, we need to remove them from the workflow actions.
And we need to do a new release for the same
@JuanVqz What do you think about the kind of release required for this? major, minor or patch?

**Comment by JuanVqz** [comment]
This is such a great question, I think it requires a mayor release.

Do you agree?

**Comment by JuanVqz** [comment]
I still thinking about the topic, we don't have any functionality that requires removing Node 12 yet I think we can still support it until that changes.
