### ISSUE TITLE
Facing the following error in Arch Linux

### ISSUE THREAD

**Issue by sakthimaan** [rajasegar/alacritty-themes#15]
Facing the following error in Arch Linux

❯ node --version
v15.12.0
~
❯ npm --version
7.7.4

![image](https://user-images.githubusercontent.com/14888257/112419901-3ae73e00-8d52-11eb-92c6-8d111089342a.png)

**Comment by rajasegar** [comment]
Related to #12

**Comment by rajasegar** [comment]
Looks like there is no `alacritty.yml` file or it might be empty.
Can you try creating one with this
```
alacritty-themes --create
```
and then try the themes

**Comment by rajasegar** [comment]
Assuming the issue has been resolved and closing it. Please feel free to reopen if it still persists.
