### ISSUE TITLE
use_thin_strokes has been removed.

### ISSUE THREAD

**Issue by rohithvishaal** [rajasegar/alacritty-themes#169]
### Change in the Config File: alacritty.yml

use_thin_strokes has been removed; Set the AppleFontSmoothing user default instead

### To Reproduce

```alacritty-themes --create```

1. Installation

- [ ] I installed it via npm i -g alacritty-themes (global installation)

### Expected behavior

Expected to show no error warning after changing the theme.

### Operating System:
- [ ] Ubuntu

### Add your alacritty.yml content

```yml
# defective line 
use_thin_strokes: true
```

### Screenshots

Before Resolving the Warning:
![image](https://user-images.githubusercontent.com/45295509/180608995-2a457204-7027-4242-b949-3215cc8ec9f0.png)

After Resolving the warning:
![image](https://user-images.githubusercontent.com/45295509/180609018-6fc83dc6-eeac-46b8-97a7-07ac61cce93b.png)

Replaced the line : 
```
use_thin_strokes: true
# Replaced the above line with
AppleFontSmooting: true
```
in ~/.config/alacritty/alacritty.yml

**Comment by JuanVqz** [comment]
Hey! Thank you for opening this issue I'll fix it as soon as possible 🧐

**Comment by JohnnyHall** [comment]
Thanks a lot for the help!!

**Comment by PranavBhattarai** [comment]
Just got an update on Alacritty ver **0.10.0** to **0.12.0** in Fedora 38.

I met this bug/warning EVERY time, I open the terminal. 
Thank you for opening the issue. 

The only small mistake you (@rohithvishaal) did above is a spelling mistake in "Smoothing":
> AppleFontSmooting: true
Instead, it should be:
> AppleFontSmoothing: true

_Minor typo._
