### ISSUE TITLE
It crashes after selecting a theme 

### ISSUE THREAD

**Issue by roetlich** [rajasegar/alacritty-themes#2]
I did a fresh install via `npm i -g alacritty-themes`, but after selecting a theme it just crashes. Output:

```
$  alacritty-themes
? Select a theme: Argonaut
/home/till/.node_modules/lib/node_modules/alacritty-themes/index.js:24
  colors.value = themeColors.value;
               ^

TypeError: Cannot set property 'value' of undefined
    at updateTheme (/home/till/.node_modules/lib/node_modules/alacritty-themes/index.js:24:16)
    at /home/till/.node_modules/lib/node_modules/alacritty-themes/index.js:64:7
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```

**Comment by rajasegar** [comment]
@roetlich It could probably due to the `colors` key in your `alacritty.yml` might be commented out. Can you please uncomment it and check. I should have handled this case :(

**Comment by rajasegar** [comment]
Closed by https://github.com/rajasegar/alacritty-themes/commit/4020123aa15523d479a44c090898048f4c8ef999

**Comment by roetlich** [comment]
Yes, this fixed it! :+1:
