### ISSUE TITLE
is the master branch protected to doesn't push to it?

### ISSUE THREAD

**Issue by JuanVqz** [rajasegar/alacritty-themes#222]
### Describe the bug

It seems the publishing workflow [has been failing](https://github.com/rajasegar/alacritty-themes/actions/runs/3981333239/jobs/6825005967) because there is a rule that requires at least 1 approving review.

```
stderr: 'remote: error: GH006: Protected branch update failed for refs/heads/master.        \n' +
    'remote: error: At least 1 approving review is required by reviewers with write access.        \n' +
    'To [https://github.com/rajasegar/alacritty-themes\n](https://github.com/rajasegar/alacritty-themes/n)' +
    ' ! [remote rejected] HEAD -> master (protected branch hook declined)\n' +
    "error: failed to push some refs to 'https://github.com/rajasegar/alacritty-themes'",
 ```

### To Reproduce

Merge a PR into the master branch

### Possible test case

Could you please deactivate the require at least 1 approving review feature, then merge a PR and see if it works?

### Expected behavior

The publishing workflow should work

**Comment by JuanVqz** [comment]
@rajasegar, just wanted to mention that recently reached the same issue, and dug a little bit.


Found this: [Only the auth-only level of npm two-factor authentication is supported, semantic-release will not work with the default auth-and-writes level.](https://github.com/semantic-release/npm)

That should be changed in your npm account to make it works back.

Reference:

- https://docs.npmjs.com/about-two-factor-authentication

**Comment by rajasegar** [comment]
@JuanVqz I have enabled 2FA for my npm account, can you please check and confirm?
