### ISSUE TITLE
Applying a theme removes all comments in alacritty.yml

### ISSUE THREAD

**Issue by ewal** [rajasegar/alacritty-themes#30]
Hey, love the package but, I tend to use a lot of comments in my dotfiles and they're removed when a theme is applied. Would be nice if only the `colors` section was modified.

**Comment by JuanVqz** [comment]
@ewal thank you for open this issue, we are glad to announce to you this has been solved 🥳

we need some testers to confirm, if you have the opportunity once #42 is merged you can give us some feedback, ✌!

**Comment by ewal** [comment]
Ah man, missed your previous reply. So nice of you for fixing this 🎉
