### ISSUE TITLE
Add an accompanying generated comment for better identification

### ISSUE THREAD

**Issue by detj** [rajasegar/alacritty-themes#54]
**Is your feature request related to a problem? Please describe.**

The way I see it, Alacritty encourages its users to fiddle around and manage its configuration by editing the Alacritty config file as they see fit. And `alacritty-themes` is essentially a yaml file patcher, patching the correct "colors" dictionary in the Alacritty config file, as per the user's input.

As of today, there is no way for users to notice and remember that these modifications was made automatically for them by a tool. They may not remember later if they had copy/pasted the colors manually or how it was updated.

**Describe the solution you'd like**

Leaving a comment may remind the user that they have the option to use `alacritty-themes` again to change the theme, without manually needed to make the edits.

I would say it is generally a good etiquette for a bot/program to communicate and let humans know that it made the edit. This way users are comfortably aware that they are not the only one editing the config file. As a side-effect, the comment can be used to provide additional instructions and so on for the user. It also looks cleaner & structured.

_before_
![Screen Shot 2021-10-31 at 3 09 38 PM](https://user-images.githubusercontent.com/280236/139576573-c81d1513-cdce-44ae-97f7-30449baea6c7.png)

_after_
![Screen Shot 2021-10-31 at 3 12 16 PM](https://user-images.githubusercontent.com/280236/139576580-9b31648a-533c-4bbd-96b2-912168940578.png)

Don't have much opinion on the comment message. Change it accordingly.

**Describe alternatives you've considered**

Alternative would be to not add any yaml comments. If there is a good reason not do add any, would certainly like to know. But then the problem remains that one cannot tell just by looking at the Alacritty config file, who made the color edits.

**Additional context**
There is no apparent harm if the user deletes the comment, or modifies it. `alacritty-themes` can choose to gracefully handle that situation. But then again, I would argue most users will not mind an auto-generated comment and would leave it as is.
Goes without saying that `alacritty-themes` should not duplicate the comment. That would be terrible.

**Comment by JuanVqz** [comment]
If anyone has an idea how to implement this in the future feel free to open a new issue/pr.
