### ISSUE TITLE
Permission to add a theme

### ISSUE THREAD

**Issue by tiagaoalb** [rajasegar/alacritty-themes#62]
I would like to have permission to add a theme.

I already cloned and added the palenight.yml locally.
If thats ok of course.

If that is not possible, could you add a Palenight theme?

**Comment by JuanVqz** [comment]
Sure! Open a PR, please.

**Comment by tiagaoalb** [comment]
> Sure! Open a PR, please.

I can't because I don't have permission.

**Comment by JuanVqz** [comment]
I'm just guessing, did you clone the https://github.com/rajasegar/ alacritty-themes repository instead of fork it?


If you are online I can show you how to do it in a video chat... let me create the link

**Comment by JuanVqz** [comment]
https://meet.jit.si/NegativeBrushesInformHalfway

**Comment by JuanVqz** [comment]
1. ![image](https://user-images.githubusercontent.com/7331511/140660037-45786eb8-f833-420d-8bbb-299e1a21edb4.png)

2. it will create a cloned repo in your Github account something like https://github.com/tiagaoalb/alacritty-themes then you can clone it in you machine

3. create a branch, then make your code (add the theme you want to add to the alacritty-themes repo)

4. push it to GitHub,  you should see an alert asking you to create a Pull Request into `rajasegar/alacritty-themes` then you create it ant that's all.

**Comment by tiagaoalb** [comment]
> I'm just guessing, did you clone the https://github.com/rajasegar/ alacritty-themes repository instead of fork it?

Yes..., ok.

**Comment by tiagaoalb** [comment]
@JuanVqz, waiting your CR.
