### ISSUE TITLE
How to use a theme that I just added to the repo?

### ISSUE THREAD

**Issue by tiagaoalb** [rajasegar/alacritty-themes#64]
I uninstalled the package and installed again, but the palenight theme is not there.
What should I do?

**Comment by JuanVqz** [comment]
Good question I was about to let you know that, your theme won't be available until the next [release](https://semver.org/), we and almost all packages (at least the ones I have been working) work with releases.

I'm not sure if we should release a new 4.1.x patch when we introduce a new theme, @rajasegar what do you think?

BTW, for that, you should stay stick to the  [commitlint](https://github.com/conventional-changelog/commitlint) standard.

**Comment by JuanVqz** [comment]
it would be good if instead of using issues, you can move your questions over the Discussions tab in the correct category, please

**Comment by rajasegar** [comment]
@JuanVqz Sounds good to me :+1:
