### ISSUE TITLE
GitHub Themes

### ISSUE THREAD

**Issue by puppeteer701** [rajasegar/alacritty-themes#75]
**Describe the solution you'd like**
Would it be possible to add GitHub themes to selection. One of the example of color schemes can be found here https://github.com/projekt0n/github-nvim-theme/tree/main/extras/alacritty.

**Comment by JuanVqz** [comment]
hey @puppeteer701, yes we are open to accepting new themes, I thought we already have the GitHub themes but not.

your Pull Request is always welcome, thanks!

**Comment by JuanVqz** [comment]
Hello @puppeteer701 we added GitHub color schemes here #78
