### ISSUE TITLE
Backspace doesn't work properly after install 

### ISSUE THREAD

**Issue by gungaii** [rajasegar/alacritty-themes#76]
After I installed alacritty themes the backspace doesn't delete the words it works as a space now

**Comment by gungaii** [comment]
Ok found this out my self if you go to alacritty.yml and add a # in front of TERM it will let you delete

**Comment by JuanVqz** [comment]
Hi @gungaii, I don't get it, at the end is it an issue in alacrity-themes or it isn't?
