### ISSUE TITLE
Suggestion: Live preview

### ISSUE THREAD

**Issue by eggbean** [rajasegar/alacritty-themes#8]
This makes it easy to apply different themes, but it is still a chore finding one I like.

If this had an option to apply the theme (make changes to config) as it is selected, that would make it a lot quicker to use. As alacritty already applies configuration changed immediately while running, this might be possible?

**Comment by rajasegar** [comment]
Fixed in 3.0.0

**Comment by eggbean** [comment]
Excellent, thanks a lot!
